server:
  port: 8090
  servlet:
    context-path: /
spring:

  mvc:         #引入mvn配置
    view:
      prefix: /WEB-INF/     # /默认代表根目录 src/main/webapp
      suffix: .jsp
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root


mybatis-plus:
  #定义别名包简化resultType的配置（自动添加前缀）
  type-aliases-package: com.huawei.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射  去除字段中的“_” 可以自动大写
  configuration:
    map-underscore-to-camel-case: true

#添加日志
logging:
  level:
    com.jd.mapper: debug